FileVersion = 1
Dependencies = {corlib = "*", OpenAL = "*", Windows = "*"}

[Project]
Name = "BfEngine"
TargetType = "BeefLib"
StartupObject = "BfEngine.Program"

[[ProjectFolder.Items]]
Type = "IgnoreSource"
Name = "lodepng.bf"
