FileVersion = 1
Dependencies = {corlib = "*", Windows = "*", ImGui = "*", ImGuiImplOpenGL3 = "*"}

[Project]
Name = "BfEngine"
TargetType = "BeefLib"
StartupObject = "BfEngine.Program"

[Configs.Debug.Win64]
OptimizationLevel = "O3"

[[ProjectFolder.Items]]
Type = "AutoFolder"
Name = "Audio"

[[ProjectFolder.Items.Items]]
Type = "IgnoreSource"
Name = "Ogg.bf"

[[ProjectFolder.Items.Items]]
Type = "IgnoreSource"
Name = "VorbisDecoder.bf"
